backend:
  name: github
  repo: sunrisemovement/pledge-to-vote-2020
local_backend: true
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
  - label: Config
    name: config
    files:
      - label: Config
        name: config
        file: content/config.json
        fields:
          - label: Example
            name: example
            widget: string
