backend:
  name: github
  repo: sunrisemovement/pledge-to-vote-2020
  branch: main
local_backend: true
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
  - label: Pages
    name: pages
    files:
      - label: Landing
        name: landing
        file: content/landing.md
        fields:
          - label: Content
            name: body
            widget: markdown
